//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer_Benutzer
    {
        public Benutzer_Benutzer()
        {
            this.tblMandantenBenutzerModules = new HashSet<MandantenBenutzerModule_Benutzer>();
        }
    
        public int BenutzerId { get; set; }
        public string Mail { get; set; }
        public string Passwort { get; set; }
        public int MandantId { get; set; }
        public System.DateTime LetzteAnmeldung { get; set; }
        public System.DateTime Erstellt { get; set; }
        public bool Aktiv { get; set; }
        public string PageStyle { get; set; }
        public string BenutzerName { get; set; }
    
        public virtual Mandanten_Benutzer tblMandanten { get; set; }
        public virtual ICollection<MandantenBenutzerModule_Benutzer> tblMandantenBenutzerModules { get; set; }
    }
}
