//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laender
    {
        public Laender()
        {
            this.Mitglieders = new HashSet<Mitglied>();
        }
    
        public int LandId { get; set; }
        public string LandName { get; set; }
    
        public virtual ICollection<Mitglied> Mitglieders { get; set; }
    }
}
