//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandanten_Benutzer
    {
        public Mandanten_Benutzer()
        {
            this.tblBenutzers = new HashSet<Benutzer_Benutzer>();
            this.tblMandantenModules = new HashSet<MandantenModule_Benutzer>();
            this.tblMandantenAdressens = new HashSet<MandantenAdressen>();
        }
    
        public int MandantId { get; set; }
        public string MandantName { get; set; }
        public System.DateTime ErstelltAm { get; set; }
        public bool Aktive { get; set; }
        public int AnzahlMitgliederMax { get; set; }
    
        public virtual ICollection<Benutzer_Benutzer> tblBenutzers { get; set; }
        public virtual ICollection<MandantenModule_Benutzer> tblMandantenModules { get; set; }
        public virtual ICollection<MandantenAdressen> tblMandantenAdressens { get; set; }
    }
}
