//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandantAdressTypen
    {
        public MandantAdressTypen()
        {
            this.MandantenAdressens = new HashSet<MandantenAdressen>();
        }
    
        public int MandantAdressTypeId { get; set; }
        public string MandantAdressTypeName { get; set; }
    
        public virtual ICollection<MandantenAdressen> MandantenAdressens { get; set; }
    }
}
