//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandantenModule_Benutzer
    {
        public int MandantModulId { get; set; }
        public int MandantId { get; set; }
        public int ModulId { get; set; }
    
        public virtual Mandanten_Benutzer tblMandanten { get; set; }
        public virtual Module_Benutzer tblModule { get; set; }
    }
}
