//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandantenAdressen
    {
        public int MandantAdressId { get; set; }
        public int MandantId { get; set; }
        public int MandantAdressTypeId { get; set; }
        public bool Standart { get; set; }
        public string Anrede { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Strasse { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Postfach { get; set; }
        public string AdresseZusatz { get; set; }
        public string NameZusatz { get; set; }
        public string Mail { get; set; }
    
        public virtual MandantAdressTypen MandantAdressTypen { get; set; }
        public virtual Mandanten_Benutzer Mandanten { get; set; }
    }
}
