//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitglied
    {
        public Mitglied()
        {
            this.RessortMandantMitglieders = new HashSet<RessortMandantMitglieder>();
        }
    
        public int MitgliedId { get; set; }
        public int MandantId { get; set; }
        public int AnredeId { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string ZusatzName { get; set; }
        public string Strasse { get; set; }
        public string Plz { get; set; }
        public string Ort { get; set; }
        public string Geburtstag { get; set; }
        public string Mail { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public int MitgliedschaftTypeId { get; set; }
        public System.DateTime RechnungsDatum { get; set; }
        public string TelefonP { get; set; }
        public string TelefonG { get; set; }
        public string Bemerkung { get; set; }
        public int MandantBenuterGruppeId { get; set; }
        public int LandId { get; set; }
    
        public virtual Anrede Anrede { get; set; }
        public virtual Mandant Mandanten { get; set; }
        public virtual MitgliedschaftType MitgliedschaftType { get; set; }
        public virtual MandantenBenutzerGruppen MandantenBenutzerGruppen { get; set; }
        public virtual Laender Laender { get; set; }
        public virtual ICollection<RessortMandantMitglieder> RessortMandantMitglieders { get; set; }
    }
}
