//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VereinDataRootDBEntities : DbContext
    {
        public VereinDataRootDBEntities()
            : base("name=VereinDataRootDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer_Benutzer> Benutzer_Benutzer { get; set; }
        public virtual DbSet<Mandanten_Benutzer> Mandanten_Benutzer { get; set; }
        public virtual DbSet<MandantenBenutzerModule_Benutzer> MandantenBenutzerModule_Benutzer { get; set; }
        public virtual DbSet<MandantenModule_Benutzer> MandantenModule_Benutzer { get; set; }
        public virtual DbSet<Module_Benutzer> Module_Benutzer { get; set; }
        public virtual DbSet<TreeNavigation> TreeNavigations { get; set; }
        public virtual DbSet<MandantAdressTypen> MandantAdressTypens { get; set; }
        public virtual DbSet<MandantenAdressen> MandantenAdressens { get; set; }
    }
}
