//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Benutzer
    {
        public Module_Benutzer()
        {
            this.tblMandantenBenutzerModules = new HashSet<MandantenBenutzerModule_Benutzer>();
            this.tblMandantenModules = new HashSet<MandantenModule_Benutzer>();
        }
    
        public int ModulId { get; set; }
        public string ModulName { get; set; }
        public int Sort { get; set; }
        public string ControlerName { get; set; }
        public string ActionName { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual ICollection<MandantenBenutzerModule_Benutzer> tblMandantenBenutzerModules { get; set; }
        public virtual ICollection<MandantenModule_Benutzer> tblMandantenModules { get; set; }
    }
}
