//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RessortMandantMitglieder
    {
        public int RessortMandantMitgliedId { get; set; }
        public int RessortId { get; set; }
        public int MandantId { get; set; }
        public int MitgliedId { get; set; }
    
        public virtual Mitglied Mitglieder { get; set; }
        public virtual Ressort Ressort { get; set; }
    }
}
