//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ressort
    {
        public Ressort()
        {
            this.RessortMandantMitglieders = new HashSet<RessortMandantMitglieder>();
        }
    
        public int RessortId { get; set; }
        public string RessortName { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<RessortMandantMitglieder> RessortMandantMitglieders { get; set; }
    }
}
