//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNavigation
    {
        public int TreeId { get; set; }
        public int TreeNavigationId { get; set; }
        public string DisplayNameDe { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public int Sort { get; set; }
        public int BenutzerRolleId { get; set; }
        public bool Aktiv { get; set; }
    }
}
